services:
  rabbit:
    image: "rabbitmq:3.12-management"
    container_name: "rabbit"
    ports:
      - "${RABBIT_PORT_EXT}:5672"
      - "1${RABBIT_PORT_EXT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    volumes:
      - rabbit_volume:/var/lib/rabbitmq
    restart: always
volumes:
  rabbit_volume: