spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "rootbot"
    password: "WHYSOserious&112233"
  application:
    name: fbot
  output:
    ansi:
      enabled: always
  profiles:
    default: "dev"

server:
  port: 8181

logging:
  level:
    root: DEBUG


telegram:
  bot:
    token: ${BOT_TOKEN}
    name: ${BOT_NAME}
    creatorId: ${CREATOR_ID}