spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASS}
  application:
    name: fbot
  output:
    ansi:
      enabled: always
  profiles:
    default: "dev"

server:
  port: ${APP_PORT}

logging:
  level:
    root: DEBUG

telegram:
  bot:
    token: ${BOT_TOKEN}