spring:
  datasource:
    url: "jdbc:h2:mem:sdb;DB_CLOSE_DELAY=-1"
    username: "bot"
    password: "BOTspring9295"
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

liquibase:
  enabled: false

